# syntax=docker/dockerfile:1
FROM python:3

ENV PYTHONUNBUFFERED=1
COPY .env.app app/.env

WORKDIR /api

COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/

RUN python manage.py migrate
RUN python manage.py sync $(date +"%s")

RUN python manage.py runserver